version: '2'
services:
  neo4j:
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "n10s", "graph-data-science"]
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/bitnami'
volumes:
  neo4j_data:
    driver: local
